// Command gen-options generates pkg/rclone/options_gen.go from `rclone config providers`.
//
//	rclone config providers | go run ./hack/gen-options v1.74.3 > pkg/rclone/options_gen.go
//
// Review the diff after an rclone update: options added to a backend are allowed unless deny matches them.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"regexp"
	"sort"
)

var backends = []string{"s3", "google cloud storage", "azureblob", "b2", "swift", "webdav", "sftp", "ftp",
	"drive", "onedrive", "dropbox", "crypt"}

// Local files, commands, local sockets, the node's cloud identity, and URLs that rclone sends credentials to
var deny = regexp.MustCompile(`_file$|_path$|command|^ssh$|^server_command$|^set_env$|^path_override$|^copy_is_hardlink$` +
	`|^key_use_agent$|^unix_socket$|_proxy$|^use_emulator$` +
	`|^env_auth$|^use_msi$|^msi_|^use_az$|^profile$|^role_|^connection_string$` +
	`|^sdk_log_mode$|^auth_url$|^token_url$|^sts_endpoint$|_iam_endpoint$`)

type provider struct {
	Name    string
	Prefix  string
	Options []struct{ Name string }
}

func main() {
	if len(os.Args) != 2 {
		log.Fatal("usage: rclone config providers | gen-options <rclone version>")
	}
	var providers []provider
	if err := json.NewDecoder(os.Stdin).Decode(&providers); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("// Code generated by hack/gen-options from rclone %s; DO NOT EDIT.\n\npackage rclone\n\n", os.Args[1])
	fmt.Println("var backendSchemas = map[string]backendSchema{")
	byName := map[string]provider{}
	for _, p := range providers {
		byName[p.Name] = p
	}
	for _, name := range backends {
		p, ok := byName[name]
		if !ok {
			log.Fatalf("backend %q not found", name)
		}
		var options []string
		for _, o := range p.Options {
			if !deny.MatchString(o.Name) {
				options = append(options, o.Name)
			}
		}
		sort.Strings(options)
		fmt.Printf("\t%q: {prefix: %q, options: set(\n", name, p.Prefix)
		for _, o := range options {
			fmt.Printf("\t\t%q,\n", o)
		}
		fmt.Println("\t)},")
	}
	fmt.Println("}")
}
