# This YAML defines all API objects to create RBAC roles for CSI node plugin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-nodeplugin-rclone
  namespace: csi-rclone
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nodeplugin-rclone
  namespace: csi-rclone
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["rclone-secret"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nodeplugin-rclone
  namespace: csi-rclone
subjects:
  - kind: ServiceAccount
    name: csi-nodeplugin-rclone
    namespace: csi-rclone
roleRef:
  kind: Role
  name: csi-nodeplugin-rclone
  apiGroup: rbac.authorization.k8s.io
